"""Generate publication figures for the GMC manuscript.

Reads the per-method summary CSVs from Results/summaries/ (data-driven, matching
the manuscript tables exactly) and writes two figures to papers/figures/:

  fig2_main.{pdf,svg,png}       — AUPR comparison, GMC vs published
                                  baselines on all four datasets (2x2 panels)
  fig3_ablation.{pdf,svg,png}   — unified-config ablation (2x2, one panel per
                                  dataset, fresh validation folds)

SGLP is deliberately excluded: it is the predecessor of GMC (replaced, not a
comparison baseline). The ablation bars shown are GMC's three architectural
components only (cold-start fill / block view / tensor view); the rank-vs-raw
fusion check is neutral and reported in prose, not plotted.

Note: fig1_framework is hand-drawn (PPTX → PDF), not generated by this script.

Run:  python scripts/make_figures.py
"""
import os

import numpy as np
import pandas as pd
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt

# LaTeX-style math (Computer Modern via mathtext — vector outlines, no local
# TeX distribution needed). Keeps math glyphs consistent across all figures.
matplotlib.rcParams["mathtext.fontset"] = "cm"

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
RES = os.path.join(ROOT, "Results", "summaries")
FIG = os.path.join(ROOT, "papers", "figures")
os.makedirs(FIG, exist_ok=True)

# ---- colour palette (validated: blue/red pair passes CVD + normal-vision
# floors; grey is the deliberately-recessive neutral baseline group) ---------
C_BASE = "#7f8c8d"    # published baselines / neutral
C_GMC = "#2a78d6"     # GMC (ours)
C_BLOCK = "#3b82f6"   # block completion view (blue)
C_TENSOR = "#8b5cf6"  # tensor completion view (violet)
C_FILL = "#14b8a6"    # cold-start KNN fill
C_INPUT = "#f59e0b"   # masked input M
C_DIS = "#16a34a"     # disease similarity (green)
DARK = "#1e293b"

DATASETS = ["Fdataset", "Cdataset", "CTDdataset2023", "Ydataset"]

# internal summary tag -> display name (published baselines under our folds)
BASELINES = [
    ("baseline_BNNR", "BNNR"),
    ("baseline_OMC", "OMC"),
    ("baseline_ITRPCA", "ITRPCA"),
    ("baseline_DNMFDDA", "DNMFDDA"),
    ("baseline_HGIMC", "HGIMC"),
    ("baseline_MSBMF", "MSBMF"),
    ("baseline_DDASKF", "DDA-SKF"),
    ("baseline_NMF-DR", "NMF-DR"),
    ("multiGMF_full", "multiGMF"),
]
# one unified GMC config on all four datasets (2026-08-11 adoption); the former
# per-dataset anchors (gmc_cs_filt37 / gmc_graph_trrank_a07 / gmc_trrank) are
# superseded — see memory [[unified-gmc-config-adopted]].
GMC_TAG = {ds: "gmc_unified" for ds in DATASETS}


def save_three(fig, base):
    """Save a figure as .pdf, .svg and .png (300 dpi) from the same figure."""
    fig.savefig(base + ".pdf", bbox_inches="tight")
    fig.savefig(base + ".svg", bbox_inches="tight")
    fig.savefig(base + ".png", dpi=300, bbox_inches="tight")
    print(f"  {os.path.basename(base)}.{{pdf,svg,png}}")


def load_aupr(dataset, tag):
    """(AUPR, AUPR_std) for a dataset + internal tag, or None if absent."""
    p = os.path.join(RES, f"{dataset}_{tag}_summary.csv")
    if not os.path.exists(p):
        return None
    row = pd.read_csv(p).iloc[0]
    return float(row["AUPR"]), float(row.get("AUPR_std", 0.0))


# ============================================================================
# ============================================================================
# Figure 2 — main AUPR comparison (2x2, one panel per dataset)
# ============================================================================
def fig2_main():
    fig, axes = plt.subplots(2, 2, figsize=(11.5, 6.4))
    axes = axes.ravel()
    for ax, ds in zip(axes, DATASETS):
        names, vals, errs, cols = [], [], [], []
        for tag, label in BASELINES:
            r = load_aupr(ds, tag)
            if r is None:
                continue
            names.append(label)
            vals.append(r[0])
            errs.append(r[1])
            cols.append(C_BASE)
        gmc_i = None
        tag = GMC_TAG[ds]
        r = load_aupr(ds, tag)
        names.append("GMC (ours)")
        vals.append(r[0])
        errs.append(r[1])
        cols.append(C_GMC)
        gmc_i = len(names) - 1
        ax.bar(np.arange(len(names)), vals, yerr=errs, color=cols,
               edgecolor="black", linewidth=0.5, capsize=2,
               error_kw=dict(lw=0.8))
        ax.text(gmc_i, vals[gmc_i] + errs[gmc_i] + 0.012, f"{vals[gmc_i]:.3f}",
                ha="center", fontsize=7, fontweight="bold", color=cols[gmc_i])
        ax.set_xticks(range(len(names)))
        ax.set_xticklabels(names, fontsize=6.4, rotation=40, ha="right")
        ax.set_ylim(0, 0.92)
        ax.set_title(ds, fontsize=10.5, pad=8)
        ax.set_ylabel("AUPR", fontsize=8)
        ax.grid(axis="y", ls=":", alpha=0.5)
        ax.set_axisbelow(True)
    handles = [
        plt.Rectangle((0, 0), 1, 1, facecolor=C_BASE, edgecolor="black", linewidth=0.5),
        plt.Rectangle((0, 0), 1, 1, facecolor=C_GMC, edgecolor="black", linewidth=0.5),
    ]
    fig.legend(handles, ["Published baselines", "GMC (ours)"],
               ncol=2, loc="upper center", bbox_to_anchor=(0.5, 1.0),
               fontsize=8.5, frameon=True, edgecolor="#cbd5e1")
    fig.suptitle("AUPR under 10-fold random-entry CVa (mean ± std)",
                 fontsize=11, y=1.02)
    fig.tight_layout(rect=(0, 0, 1, 0.97))
    save_three(fig, os.path.join(FIG, "fig2_main"))
    plt.close(fig)


# ============================================================================
# Figure 3 — remove-one-at-a-time ablation (2x2, one panel per dataset; data
# from the fresh validation folds, matching Table 2 + ablation narrative)
# ============================================================================
# Each ablation starts from the FULL unified model (mode 0 = uni_obs_rc400_t50:
# fill=knn + block + tensor + rank fusion) and removes EXACTLY ONE architectural
# component (2026-08-16 refactor from the old add-a-rung ladder):
#   mode A  −fill    = ablate_fill       (fill="none")
#   mode B  −block   = ablate_block      (w_bnnr=0, tensor-only)
#   mode C  −tensor  = uni_obs_rc400_nt  (w_tensor=0, block-only)
# The scale-free rank fusion is NOT an architectural component — it is a numerical
# detail (rank normalization before the fixed 0.5/0.5 weight). Its raw-vs-rank
# check (ablate_fusion) is neutral (|Δ|≤0.0003) and is reported in prose only,
# not as a 4th bar. uni_obs_rc400_nofill (removes BOTH fill and tensor) is a
# superseded control and no longer plotted.
ABLATION_MODES = [
    ("uni_obs_rc400_t50", "full", C_GMC),      # GMC 完整模型
    ("ablate_fill",       "model A", "#8fb3c9"),
    ("ablate_block",      "model B", "#7f9cb5"),
    ("uni_obs_rc400_nt",  "model C", "#a895c9"),
]


def _fresh_aupr(ds, config):
    """AUPR for a unified-scope config on the fresh validation folds."""
    p = os.path.join(RES, f"{ds}_unified_fresh_summary.csv")
    if not os.path.exists(p):
        return None
    df = pd.read_csv(p)
    row = df[df["config"] == config]
    if row.empty:
        return None
    return float(row["AUPR"].iloc[0])


def _ablation_bar(ax, ds, vals, labels, cols, ymax):
    bars = ax.bar(range(len(vals)), vals, color=cols, edgecolor="black",
                  linewidth=0.5, width=0.62)
    for i, v in enumerate(vals):
        ax.text(i, v + ymax * 0.025, f"{v:.4f}", ha="center", fontsize=7,
                fontweight="bold")
    ax.set_xticks(range(len(vals)))
    ax.set_xticklabels(labels, fontsize=7.4)
    ax.set_ylim(0, ymax)
    ax.set_title(ds, fontsize=10.5)
    ax.set_ylabel("AUPR", fontsize=8.5)
    ax.grid(axis="y", ls=":", alpha=0.5)
    ax.set_axisbelow(True)
    return bars


def fig3_ablation():
    fig, axes = plt.subplots(2, 2, figsize=(12.0, 6.0))
    axes = axes.ravel()
    labels = [m[1] for m in ABLATION_MODES]
    cols = [m[2] for m in ABLATION_MODES]
    for ax, ds in zip(axes, DATASETS):
        vals = [_fresh_aupr(ds, m[0]) for m in ABLATION_MODES]
        if any(v is None for v in vals):
            ax.text(0.5, 0.5, f"incomplete ablation for {ds}", ha="center",
                    va="center", transform=ax.transAxes, fontsize=9, color="#dc2626")
            continue
        _ablation_bar(ax, ds, vals, labels, cols, 0.85)
    handles = [
        plt.Rectangle((0, 0), 1, 1, facecolor=C_GMC, edgecolor="black", linewidth=0.5),
        plt.Rectangle((0, 0), 1, 1, facecolor="#8fb3c9", edgecolor="black", linewidth=0.5),
        plt.Rectangle((0, 0), 1, 1, facecolor="#7f9cb5", edgecolor="black", linewidth=0.5),
        plt.Rectangle((0, 0), 1, 1, facecolor="#a895c9", edgecolor="black", linewidth=0.5),
    ]
    fig.legend(handles,
               ["full (GMC)", "A − cold-start KNN fill",
                "B − block completion view", "C − tensor completion view"],
               ncol=2, loc="upper center", bbox_to_anchor=(0.5, 1.0),
               fontsize=7.6, frameon=True, edgecolor="#cbd5e1")
    fig.suptitle("Remove-one-module ablation of GMC (AUPR, fresh validation folds)",
                 fontsize=11, y=1.04)
    fig.tight_layout(rect=(0, 0, 1, 0.97))
    save_three(fig, os.path.join(FIG, "fig3_ablation"))
    plt.close(fig)


# ============================================================================
# Figure 4 — parameter sensitivity (AUPR vs each hyperparameter, one panel per
# axis; data from Results/summaries/*_param_sweep_summary.csv, fresh folds)
# ============================================================================
# Equidistant 5-point grid (2026-08-16): all five axes run on all four
# datasets. Config names encode (axis, value): alpha01/03/07/09, iter20/30/50/60,
# rc200/300/500/600, k5/15/20/25, wt01/03/07/09; the single "center" config
# (the gmc_unified center on every axis) is reused across all five panels.
AXES = [
    ("alpha",   r"$\alpha$",   0.5),
    ("maxiter", "maxiter",     40),
    ("rc",      "rank cap",    400),
    ("k",       "k (fill)",    10),
    ("wt",      r"$w_t$",      0.5),
]
# config-name suffix -> numeric value on each axis (generalized decoder)
_AXIS_DECODE = {
    "alpha": lambda s: 0.1 * int(s),            # 01,03,07,09 -> 0.1..0.9
    "maxiter": lambda s: int(s),                # 20,30,50,60
    "rc": lambda s: int(s),                     # 200,300,500,600
    "k": lambda s: int(s),                      # 5,15,20,25
    "wt": lambda s: 0.1 * int(s),               # 01,03,07,09 -> 0.1..0.9
}
# config-name prefix -> axis key (iter -> maxiter; the rest are the axis name)
_AXIS_PREFIX = {"alpha": "alpha", "iter": "maxiter",
                "rc": "rc", "k": "k", "wt": "wt"}
DS_COLORS = {"Fdataset": C_GMC, "Cdataset": C_DIS,
             "CTDdataset2023": C_TENSOR, "Ydataset": C_INPUT}


def _param_pts(ds):
    """{(axis, value): AUPR} from the param-sweep summary for one dataset.

    The "center" config (== gmc_unified) maps to every axis's center value, so
    each 4-point grid line gains its shared center point.
    """
    p = os.path.join(RES, f"{ds}_param_sweep_summary.csv")
    if not os.path.exists(p):
        return {}
    df = pd.read_csv(p)
    out = {}
    for _, r in df.iterrows():
        cfg, v = r["config"], r["AUPR"]
        if cfg == "center":
            for key, _, center in AXES:
                out[(key, center)] = v
            continue
        for prefix, axis in _AXIS_PREFIX.items():
            if cfg.startswith(prefix) and len(cfg) > len(prefix):
                out[(axis, _AXIS_DECODE[axis](cfg[len(prefix):]))] = v
    return out


def fig4_param():
    fig, axes = plt.subplots(1, len(AXES), figsize=(15.5, 3.2))
    for ax, (key, label, center) in zip(axes, AXES):
        for ds in DATASETS:
            pts = _param_pts(ds)
            xs = sorted([x for (k, x) in pts if k == key])
            ys = [pts[(key, x)] for x in xs]
            ax.plot(xs, ys, "o-", label=ds, color=DS_COLORS[ds],
                    lw=1.6, markersize=4)
        allx = sorted({x for ds in DATASETS
                       for (k, x) in _param_pts(ds).items() if k == key})
        if key in ("alpha", "wt"):
            ax.set_xlim(0, 1)
        elif allx:
            lo, hi = min(allx), max(allx)
            pad = 0.04 * (hi - lo)
            ax.set_xlim(lo - pad, hi + pad)

        ax.axvline(center, color=DARK, ls="--", lw=1.0, alpha=0.6)
        ax.set_title(label, fontsize=9.5)
        ax.set_ylabel("AUPR" if ax is axes[0] else "", fontsize=8)
        ax.grid(axis="y", ls=":", alpha=0.5)
        ax.set_axisbelow(True)
        ax.tick_params(labelsize=7.5)
    handles = [plt.Line2D([], [], color=DS_COLORS[d], lw=1.6, label=d)
               for d in DATASETS]
    handles.append(plt.Line2D([], [], color=DARK, lw=1.0, ls="--", label="center"))
    fig.legend(handles, DATASETS + ["center"], ncol=5, loc="upper center",
               bbox_to_anchor=(0.5, 1.08), fontsize=8, frameon=True,
               edgecolor="#cbd5e1")
    fig.suptitle("Parameter sensitivity of the unified configuration (AUPR, fresh folds)",
                 fontsize=11, y=1.12)
    fig.tight_layout()
    save_three(fig, os.path.join(FIG, "fig4_param"))
    plt.close(fig)


# ============================================================================
# Figure 5 — robustness to missing data (AUPR vs held-out fraction; data from
# Results/summaries/*_robust_mask_summary.csv)
# ============================================================================
def fig5_robust():
    fig, ax = plt.subplots(figsize=(6.2, 4.2))
    for ds in DATASETS:
        p = os.path.join(RES, f"{ds}_robust_mask_summary.csv")
        if not os.path.exists(p):
            continue
        df = pd.read_csv(p).sort_values("frac")
        ax.plot(df["frac"], df["AUPR"], "o-", label=ds, lw=1.8, markersize=5)
    ax.set_xlabel("Held-out fraction (mask rate)", fontsize=9)
    ax.set_ylabel("AUPR", fontsize=9)
    ax.set_xticks([0.05, 0.10, 0.20, 0.30])
    ax.grid(ls=":", alpha=0.5)
    ax.set_axisbelow(True)
    ax.legend(fontsize=8, frameon=True, edgecolor="#cbd5e1")
    ax.set_title("Robustness to missing data (fixed unified config)",
                 fontsize=10.5)
    fig.tight_layout()
    save_three(fig, os.path.join(FIG, "fig5_robust"))
    plt.close(fig)


if __name__ == "__main__":
    print("Generating GMC figures →", FIG)
    fig2_main()
    fig3_ablation()
    fig4_param()
    fig5_robust()
    print("done.")
