"""Run GMC configuration grids on the INDEPENDENT validation folds (de-leakage).

The per-dataset GMC configurations were originally selected by inspecting
the 10-fold CVa TEST results (a reviewer vulnerability: the reported folds took
part in the selection).  This script re-does the selection on validation folds
generated by ``scripts/gen_val_folds.py`` — a fresh ~10% pos+neg hold-out inside
each fold's training entries, disjoint from the reported test indices.  The
validation winner is then frozen and reported on the ORIGINAL test folds, so the
reported numbers never participate in configuration selection.

Grids (per PROGRESS.md de-leakage plan, updated for the post-Y-strengthening state):
  F / C   : the fixed block+filter pipeline (single candidate), plus a
            block-only no-filter control on F to confirm the filter earns its
            keep on unseen folds (tensor view omitted on F/C is an a-priori
            scale rule, not a tuned choice).
  CTD     : w_bnnr in {0.1,0.2,0.3} x graph-embedding {off} or {a=0.3,0.7,1.2,2.0},
            w_tensor=0.8, tensor rank-cap 200, rank fusion.  The tensor view is
            independent of the grid, so it is computed once per fold and cached.
  Y       : full factorial over the View-A switches that define the Y config:
            fill {wknn,knn} x block {sym,dual} x trindex {all,observed}.

Usage:
    python scripts/run_gmc_val.py --datasets Fdataset Cdataset       # run grids
    python scripts/run_gmc_val.py --datasets CTDdataset2023          # run CTD grid
    python scripts/run_gmc_val.py --datasets Ydataset                # run Y grid
    python scripts/run_gmc_val.py --datasets Fdataset --save-winner  # save winner val preds
"""
import argparse
import glob
import os
import sys

import numpy as np
import pandas as pd
import scipy.io as sio

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from gmc import gmc_predict, evaluate_fold, mask_test_entries, load_sim_lists
from gmc.model import coldstart_fill, rnorm01
from gmc.wknn import wknn
from gmc.filter import sparsify_graph, normalised_laplacian
from gmc.factorization import bounded_nn_completion, bounded_nn_completion_graph, fitrpca
from gmc.helpers import FOLD_DIR, OUT_DIR, RESULT_DIR

NFOLD = 10

# ── per-dataset GMC grids ────────────────────────────────────────────────
# base completion settings shared by all CTD grid points
CTD_BASE = dict(coldstart=True, w_tensor=0.8, tensor_rank_cap=200, fusion="rank",
                bnnr_alpha=0.5, bnnr_beta=10.0, bnnr_maxiter=40, bnnr_rank_cap=160)
# base completion settings shared by all Y grid points (Y is block-only)
Y_BASE = dict(bnnr_alpha=1.0, bnnr_maxiter=100, bnnr_rank_cap=200,
              w_bnnr=1.0, fusion="raw")

GRIDS = {
    "Fdataset": [
        ("gmc_cs_filt37",
         dict(coldstart=True, wknn_k=10, wknn_r=0.9, filt_alpha=0.3, filt_beta=0.7, w_bnnr=1.0)),
        ("gmc_cs_blk_only",
         dict(coldstart=True, wknn_k=10, wknn_r=0.9, w_bnnr=1.0)),
    ],
    "Cdataset": [
        ("gmc_cs_filt37",
         dict(coldstart=True, wknn_k=30, wknn_r=0.95, filt_alpha=0.3, filt_beta=0.7, w_bnnr=1.0)),
    ],
    "CTDdataset2023": [
        ("gmc_off_w{:g}".format(w), dict(w_bnnr=w, w_graph=0.0))
        for w in (0.1, 0.2, 0.3)
    ] + [
        ("gmc_on_w{:g}_a{:s}".format(w, a), dict(w_bnnr=w, w_graph=1.0, graph_alpha=float(a)))
        for w in (0.1, 0.2, 0.3)
        for a in ("03", "07", "12", "20")
    ],
    "Ydataset": [
        ("gmc_knn_dual_obs",   dict(fill="knn",  block="dual", trindex="observed", wknn_k=10)),
        ("gmc_wknn_dual_obs",  dict(fill="wknn", block="dual", trindex="observed",
                                    wknn_k=30, wknn_r=0.95, coldstart=True)),
        ("gmc_knn_sym_obs",    dict(fill="knn",  block="sym",  trindex="observed", wknn_k=10)),
        ("gmc_knn_dual_all",   dict(fill="knn",  block="dual", trindex="all",      wknn_k=10)),
        ("gmc_wknn_sym_obs",   dict(fill="wknn", block="sym",  trindex="observed",
                                    wknn_k=30, wknn_r=0.95, coldstart=True)),
        ("gmc_wknn_dual_all",  dict(fill="wknn", block="dual", trindex="all",
                                    wknn_k=30, wknn_r=0.95, coldstart=True)),
        ("gmc_knn_sym_all",    dict(fill="knn",  block="sym",  trindex="all",      wknn_k=10)),
        ("gmc_wknn_sym_all",   dict(fill="wknn", block="sym",  trindex="all",
                                    wknn_k=30, wknn_r=0.95, coldstart=True)),
    ],
}

# ── FRESH-split adjudication grids (--fresh) ──────────────────────────────
# A FRESH independent 10-fold CVa split (same ~10% masking as the test
# protocol; seed 24680) is used to adjudicate the two config choices where the
# nested validation folds and the test folds disagreed:
#   Y  : block structure sym vs dual x rank cap {200,400} (knn fill + observed
#        mask — those switches were confirmed on the nested folds).  The
#        rank-cap dimension tests the 2026-08-10 rank-budget hypothesis
#        (sym+rc400 beat dual/orig on the test folds) on independent folds.
#        Y grid points are merged with Y_BASE (alpha=1.0, maxiter=100,
#        rank_cap=200 unless overridden) in run_grid.
#   CTD: w_bnnr 0.2 vs 0.3 (graph-embedded, a=0.7).
# F/C are already confirmed by the nested folds and need no re-adjudication.
FRESH_GRIDS = {
    "Fdataset": GRIDS["Fdataset"],
    "Cdataset": GRIDS["Cdataset"],
    "CTDdataset2023": [
        ("gmc_on_w02_a07", dict(w_bnnr=0.2, w_graph=1.0, graph_alpha=0.7)),
        ("gmc_on_w03_a07", dict(w_bnnr=0.3, w_graph=1.0, graph_alpha=0.7)),
    ],
    "Ydataset": [
        ("gmc_knn_sym_obs",    dict(fill="knn", block="sym",  trindex="observed", wknn_k=10)),
        ("gmc_knn_dual_obs",   dict(fill="knn", block="dual", trindex="observed", wknn_k=10)),
        ("gmc_knn_sym_rc400",  dict(fill="knn", block="sym",  trindex="observed", wknn_k=10,
                                    bnnr_rank_cap=400)),
        ("gmc_knn_dual_rc400", dict(fill="knn", block="dual", trindex="observed", wknn_k=10,
                                    bnnr_rank_cap=400)),
    ],
}


def _load_val(ds, fresh=False):
    fd = sio.loadmat(os.path.join(FOLD_DIR, f"folds_{ds}.mat"))
    Wdr = fd["Wdr"].astype(np.float64)
    fname = f"valfolds_fresh_{ds}.mat" if fresh else f"valfolds_{ds}.mat"
    vf = sio.loadmat(os.path.join(FOLD_DIR, fname))
    drug_sims, dis_sims = load_sim_lists(ds)
    Wrr = np.mean(drug_sims, axis=0)
    Wdd = np.mean(dis_sims, axis=0)
    return (Wdr, vf["pos_test_idx"], vf["val_pos_idx"], vf["val_idx"],
            Wrr, Wdd, drug_sims, dis_sims)


def _masked_for_val(Wdr, pos_test_f, val_pos_f):
    """Zero the test AND validation positive entries (test/val negatives are 0)."""
    pt = pos_test_f[pos_test_f >= 0].astype(int)
    vp = val_pos_f[val_pos_f >= 0].astype(int)
    return mask_test_entries(Wdr, np.union1d(pt, vp))


def _ctd_predict(masked, Wrr, Wdd, drug_sims, dis_sims, cache, w_bnnr, w_graph, graph_alpha):
    """CTD path with per-fold caching of the (grid-independent) fill and tensor view."""
    dn, dr = masked.shape
    if "filled" not in cache:
        soft = wknn(masked.T, Wrr, Wdd, k=30, r=0.95).T
        cache["filled"] = coldstart_fill(masked, soft)
    filled = cache["filled"]

    if "tensor" not in cache:
        drn, ddn = len(drug_sims), len(dis_sims)
        Trr = np.zeros((dr, dr, drn)); Tdd = np.zeros((dn, dn, ddn))
        for i, s in enumerate(drug_sims):
            Trr[:, :, i] = s
        for i, s in enumerate(dis_sims):
            Tdd[:, :, i] = s
        cache["tensor"] = fitrpca(Trr, Tdd, masked, p=0.9, K=30, rat1=0.1, rat2=0.2,
                                  rank_cap=CTD_BASE["tensor_rank_cap"])
    M_tensor = cache["tensor"]

    T = np.block([[Wdd, filled], [filled.T, Wrr]])
    trI = np.ones_like(T)
    b = CTD_BASE
    if w_graph > 0:
        Ld = normalised_laplacian(sparsify_graph(Wdd, 5))
        Lr = normalised_laplacian(sparsify_graph(Wrr, 5))
        Wc = bounded_nn_completion_graph(T, trI, Ld, Lr, dn, dr,
                                         graph_alpha=graph_alpha, alpha=b["bnnr_alpha"],
                                         beta=b["bnnr_beta"], maxiter=b["bnnr_maxiter"],
                                         rank_cap=b["bnnr_rank_cap"])
    else:
        Wc = bounded_nn_completion(T, trI, alpha=b["bnnr_alpha"], beta=b["bnnr_beta"],
                                   maxiter=b["bnnr_maxiter"], rank_cap=b["bnnr_rank_cap"])
    M_bnnr = np.clip(Wc[0:dn, dn:dn + dr], 0, 1)
    F = (w_bnnr * rnorm01(M_bnnr) + CTD_BASE["w_tensor"] * rnorm01(M_tensor)) / \
        (w_bnnr + CTD_BASE["w_tensor"])
    return np.where(masked != 0, masked, np.clip(F, 0, 1))


def run_grid(ds, quick=False, fresh=False):
    Wdr, pos_test, val_pos, val_idx, Wrr, Wdd, drug_sims, dis_sims = _load_val(ds, fresh=fresh)
    nfold = 2 if quick else NFOLD
    grid = FRESH_GRIDS[ds] if fresh else GRIDS[ds]
    tag = "fresh" if fresh else "nested"
    rows = []
    for f in range(nfold):
        masked = _masked_for_val(Wdr, pos_test[f], val_pos[f])
        cache = {}
        ind = val_idx[f]; ind = ind[ind >= 0].astype(int)
        for name, params in grid:
            if ds == "CTDdataset2023":
                M = _ctd_predict(masked, Wrr, Wdd, drug_sims, dis_sims, cache,
                                 params["w_bnnr"], params["w_graph"],
                                 params.get("graph_alpha", 0.7))
            else:
                if ds == "Ydataset":
                    params = dict(Y_BASE, **params)
                M = gmc_predict(masked, Wrr, Wdd, drug_sims, dis_sims, seed=1,
                                **params)
            res = evaluate_fold(M, Wdr, ind)
            res["fold"] = f + 1
            res["config"] = name
            rows.append(res)
        print(f"  {ds} fold{f + 1:02d}: " +
              " ".join(f"{n}={v:.4f}" for n, v in
                       sorted({r['config']: r['AUPR'] for r in rows if r['fold'] == f + 1}.items())),
              flush=True)

    ddf = pd.DataFrame(rows)
    ddf.to_csv(os.path.join(RESULT_DIR, f"{ds}_val_{tag}_fold_results.csv"), index=False)
    summ = (ddf.groupby("config").agg(
        AUPR=("AUPR", "mean"), AUROC=("AUROC", "mean"),
        AUPR_std=("AUPR", "std")).sort_values("AUPR", ascending=False))
    summ.to_csv(os.path.join(RESULT_DIR, f"{ds}_val_{tag}_summary.csv"))
    print(f"\n== {ds} {tag} validation leaderboard (mean AUPR over {nfold} folds) ==")
    for name, row in summ.iterrows():
        print(f"  {name:<20s} AUPR={row['AUPR']:.4f}  AUROC={row['AUROC']:.4f}")
    winner = summ.index[0]
    print(f"  >> winner: {winner}")
    return winner, nfold


def save_winner(ds, quick=False, fresh=False):
    """Re-run the grid winner on the validation folds and save its per-fold preds.

    Reads the winner from the summary CSV written by ``run_grid`` and re-runs
    that one config on the validation masks (so the GMC component has NOT seen
    the validation entries).
    """
    tag = "fresh" if fresh else "nested"
    summ = pd.read_csv(os.path.join(RESULT_DIR, f"{ds}_val_{tag}_summary.csv"),
                       index_col=0)
    winner = summ.index[0]
    Wdr, pos_test, val_pos, val_idx, Wrr, Wdd, drug_sims, dis_sims = _load_val(ds, fresh=fresh)
    grid = dict(FRESH_GRIDS[ds] if fresh else GRIDS[ds])
    params = dict(CTD_BASE, **{k: v for k, v in grid[winner].items()}) if ds == "CTDdataset2023" \
        else dict(Y_BASE, **grid[winner]) if ds == "Ydataset" else grid[winner]
    nfold = 2 if quick else NFOLD
    outdir = os.path.join(OUT_DIR, ds, f"val_{tag}_{winner}")
    os.makedirs(outdir, exist_ok=True)
    for f in range(nfold):
        masked = _masked_for_val(Wdr, pos_test[f], val_pos[f])
        M = gmc_predict(masked, Wrr, Wdd, drug_sims, dis_sims, seed=1, **params)
        sio.savemat(os.path.join(outdir, f"fold_{f + 1:02d}.mat"), {"M_pred": M})
    print(f"== saved winner {tag}-val preds -> Results/outputs/{ds}/val_{tag}_{winner}/")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--datasets", nargs="+", default=["Fdataset"])
    ap.add_argument("--quick", action="store_true", help="2 folds only (smoke test)")
    ap.add_argument("--fresh", action="store_true",
                    help="use the FRESH independent CVa split (adjudication grids)")
    ap.add_argument("--save-winner", action="store_true",
                    help="re-run the grid winner on val folds and save its preds")
    args = ap.parse_args()

    for ds in args.datasets:
            if args.save_winner:
                save_winner(ds, quick=args.quick, fresh=args.fresh)
            else:
                run_grid(ds, quick=args.quick, fresh=args.fresh)
